services:
  - type: web
    name: agriquest
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python migrate_to_postgresql.py
    startCommand: python run.py
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /
    autoDeploy: true
