apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      queryTimeout: 60s
      timeInterval: 5s
    secureJsonData: {}
    
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: db:5432
    database: agriquest
    user: agriquest
    isDefault: false
    editable: true
    jsonData:
      sslmode: disable
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
    secureJsonData:
      password: ${POSTGRES_PASSWORD}

